"""Generate ``docs/runs/scenario-a.md`` — the recorded run the brief asks for.

The deliverable is produced *by the audit renderer, from the ledger*, rather than
written by hand. Two things follow from that:

* It cannot drift. If the code changes what the agent does, the recorded run
  changes with it on the next regeneration, and if it does not, that is a bug in
  the audit log rather than a stale document.
* It is a demonstration of requirement 7. The renderer reads only
  ``audit_events`` — no runs table, no proposals table, no systems of record — so
  the fact that a readable narrative comes out at all is the evidence that the
  ledger is sufficient on its own.
"""

from __future__ import annotations

import io
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from harmony.kernel.config import load_env  # noqa: E402

load_env(REPO)  # so `.env` works here exactly as it does for the CLI

from rich.console import Console  # noqa: E402

from harmony.audit.explain import RunExplainer  # noqa: E402
from harmony.runtime.run import TriggerKind  # noqa: E402
from northfield.demo.scenario_a import run_scenario_a  # noqa: E402

OUTPUT = REPO / "docs" / "runs"


def main() -> int:
    report = Console()
    workdir = Path(tempfile.mkdtemp(prefix="harmony-recorded-"))

    # Run the scenario for real, silently, then render what it left behind.
    silent = Console(file=io.StringIO(), width=100)
    run = run_scenario_a(silent, db_path=str(workdir / "recorded.db"))
    if run is None:
        report.print("[red]scenario A did not complete[/red]")
        return 1

    # Reopen the same database, so the renderer sees exactly what a reviewer
    # running `harmony audit explain` would see.
    from harmony.llm.replay import build_client
    from harmony.runtime.discovery import load_deployment
    from harmony.runtime.harness import Harness

    reopened = Harness.build(
        load_deployment(),
        db_path=workdir / "recorded.db",
        llm=build_client(),
        seed=False,
    )
    explainer = RunExplainer(reopened.audit_log)

    OUTPUT.mkdir(parents=True, exist_ok=True)
    sections: list[str] = [
        "# Recorded run — Scenario A",
        "",
        "Generated by `make recorded-run`. Every line below is rendered from the",
        "`audit_events` table alone: the renderer reads no other table, which is how",
        "requirement 7 — *\"from the audit log alone, someone should be able to",
        "reconstruct what the agent saw, what it concluded, what it was allowed to do,",
        "who approved what, and what actually happened in each system\"* — is",
        "demonstrated rather than claimed.",
        "",
        "The model's side of every exchange came from `cassettes/`, so this run is",
        "reproducible: `make demo-a` produces the same identifiers and the same",
        "narrative.",
        "",
        "---",
        "",
    ]

    followups = [
        r
        for r in reopened.runs.recent(20)
        if r.trigger is TriggerKind.FOLLOW_UP and r.parent_run_id == run.run_id
    ]

    sections.append(explainer.explain_markdown(run.run_id))
    for follow_up in followups:
        sections += [
            "",
            "---",
            "",
            "## The scheduled follow-up",
            "",
            "A separate run, opened days later by the arrival check the workflow",
            "scheduled. It went through detection, planning, gating and approval",
            "exactly as the first one did — a follow-up is a targeted detection, not a",
            "special mechanism.",
            "",
            explainer.explain_markdown(follow_up.run_id),
        ]

    path = OUTPUT / "scenario-a.md"
    path.write_text("\n".join(sections), encoding="utf-8")

    events = len(reopened.audit_log.for_run(run.run_id))
    report.print(f"[green]wrote {path} — {events} events, {len(followups)} follow-up run(s)[/green]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
